# Generated by Django 4.2.7 on 2024-02-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department_studentid_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentId',
        ),
    ]
